
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:22 (project)"
    message: |
      The target system is: Generic -  - 
      The host system is: Darwin - 24.6.0 - arm64
  -
    kind: "message-v1"
    backtrace:
      - "/Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:22 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /Users/yildirim/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.24.0/bin//armclang 
      Build flags: --target=arm-arm-none-eabi;-mcpu=Cortex-M4;-mfpu=fpv4-sp-d16;-mfloat-abi=hard
      Id flags: -c;--target=arm-arm-none-eabi 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is ARMClang, found in:
        /Users/yildirim/Desktop/ITSBoard/ITS-BRD-VSC/Programs/Aufgabe1/tmp/1/CMakeFiles/3.28.4/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1168 (message)"
      - "/Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineASMCompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:22 (project)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" did not match "(GNU assembler)|(GCC)|(Free Software Foundation)":
      Product: Keil MDK Community (non-commercial free of charge)
      Component: Arm Compiler for Embedded 6.24
      Tool: armclang [5f371900]
      
      Target: unspecified-arm-none-none
  -
    kind: "message-v1"
    backtrace:
      - "/Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1168 (message)"
      - "/Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineASMCompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:22 (project)"
    message: |
      Checking whether the ASM compiler is AppleClang using "--version" did not match "(Apple (clang|LLVM) version)":
      Product: Keil MDK Community (non-commercial free of charge)
      Component: Arm Compiler for Embedded 6.24
      Tool: armclang [5f371900]
      
      Target: unspecified-arm-none-none
  -
    kind: "message-v1"
    backtrace:
      - "/Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1168 (message)"
      - "/Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineASMCompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:22 (project)"
    message: |
      Checking whether the ASM compiler is Clang using "--version" did not match "(clang version)":
      Product: Keil MDK Community (non-commercial free of charge)
      Component: Arm Compiler for Embedded 6.24
      Tool: armclang [5f371900]
      
      Target: unspecified-arm-none-none
  -
    kind: "message-v1"
    backtrace:
      - "/Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1155 (message)"
      - "/Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineASMCompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:22 (project)"
    message: |
      Checking whether the ASM compiler is ARMClang using "--version" matched "armclang":
      Product: Keil MDK Community (non-commercial free of charge)
      Component: Arm Compiler for Embedded 6.24
      Tool: armclang [5f371900]
      
      Target: unspecified-arm-none-none
  -
    kind: "try_compile-v1"
    backtrace:
      - "/Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:22 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/Users/yildirim/Desktop/ITSBoard/ITS-BRD-VSC/Programs/Aufgabe1/tmp/1/CMakeFiles/CMakeScratch/TryCompile-s6VgO2"
      binary: "/Users/yildirim/Desktop/ITSBoard/ITS-BRD-VSC/Programs/Aufgabe1/tmp/1/CMakeFiles/CMakeScratch/TryCompile-s6VgO2"
    cmakeVariables:
      CMAKE_CXX_COMPILER_TARGET: "arm-arm-none-eabi"
      CMAKE_C_COMPILER_TARGET: "arm-arm-none-eabi"
      CMAKE_C_FLAGS: "--target=arm-arm-none-eabi -mcpu=Cortex-M4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard"
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.open.cmsis.pack.cmsis.toolbox/2.12.0/etc/CMakeASM"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/Users/yildirim/Desktop/ITSBoard/ITS-BRD-VSC/Programs/Aufgabe1/tmp/1/CMakeFiles/CMakeScratch/TryCompile-s6VgO2'
        
        Run Build Command(s): /Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.ninja.build.ninja/1.12.1/ninja -v cmTC_467d5
        [1/2] /Users/yildirim/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.24.0/bin//armclang --target=arm-arm-none-eabi   --target=arm-arm-none-eabi -mcpu=Cortex-M4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard    -v -MD -MT CMakeFiles/cmTC_467d5.dir/CMakeCCompilerABI.o -MF CMakeFiles/cmTC_467d5.dir/CMakeCCompilerABI.o.d -o CMakeFiles/cmTC_467d5.dir/CMakeCCompilerABI.o -c /Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeCCompilerABI.c
        Product: Keil MDK Community (non-commercial free of charge)
        Component: Arm Compiler for Embedded 6.24
        Tool: armclang [5f371900]
        
        Target: arm-arm-none-eabi
         (in-process)
         "/Users/yildirim/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.24.0/bin/armclang" -cc1 -triple thumbv7em-arm-none-eabihf -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model static -mframe-pointer=none -menable-no-infs -menable-no-nans -fmath-errno -fno-signed-zeros -fdenormal-fp-math=preserve-sign,preserve-sign -ffp-contract=on -fno-rounding-math -ffinite-math-only -mconstructor-aliases -target-cpu cortex-m4 -target-feature -vfp2 -target-feature +vfp2sp -target-feature -vfp3 -target-feature -vfp3d16 -target-feature +vfp3d16sp -target-feature -vfp3sp -target-feature +fp16 -target-feature -vfp4 -target-feature -vfp4d16 -target-feature +vfp4d16sp -target-feature -vfp4sp -target-feature -fp-armv8 -target-feature -fp-armv8d16 -target-feature -fp-armv8d16sp -target-feature -fp-armv8sp -target-feature -fullfp16 -target-feature -fp64 -target-feature -d32 -target-feature -neon -target-feature -sha2 -target-feature -aes -target-feature -fp16fml -target-abi aapcs -mfloat-abi hard -debugger-tuning=gdb -fforce-dwarf-frame -fdebug-compilation-dir=/Users/yildirim/Desktop/ITSBoard/ITS-BRD-VSC/Programs/Aufgabe1/tmp/1/CMakeFiles/CMakeScratch/TryCompile-s6VgO2 -target-linker-version 820.1 -v -ffunction-sections -fdata-sections -fcoverage-compilation-dir=/Users/yildirim/Desktop/ITSBoard/ITS-BRD-VSC/Programs/Aufgabe1/tmp/1/CMakeFiles/CMakeScratch/TryCompile-s6VgO2 -resource-dir /Users/yildirim/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.24.0/lib/clang/20 -dependency-file CMakeFiles/cmTC_467d5.dir/CMakeCCompilerABI.o.d -MT CMakeFiles/cmTC_467d5.dir/CMakeCCompilerABI.o -sys-header-deps -internal-isystem /Users/yildirim/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.24.0/bin/../include -nobuiltininc -ferror-limit 19 -fvisibility=hidden -fno-signed-char -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fsuppress-licensing -aggressive-jump-threading -o CMakeFiles/cmTC_467d5.dir/CMakeCCompilerABI.o -x c /Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeCCompilerABI.c
        Arm Compiler for Embedded 6.24 -cc1 default target aarch64-arm-none-eabi
        #include "..." search starts here:
        #include <...> search starts here:
         /Users/yildirim/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.24.0/bin/../include
        End of search list.
        [2/2] : && /Users/yildirim/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.24.0/bin/armar --create -cr libcmTC_467d5.a  CMakeFiles/cmTC_467d5.dir/CMakeCCompilerABI.o && :
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "/Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:127 (message)"
      - "/Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:22 (project)"
    message: |
      Parsed C implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [/Users/yildirim/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.24.0/bin/../include]
        end of search list found
        collapse include dir [/Users/yildirim/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.24.0/bin/../include] ==> [/Users/yildirim/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.24.0/include]
        implicit include dirs: [/Users/yildirim/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.24.0/include]
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:159 (message)"
      - "/Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:22 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(armlink|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        ignore line: [Change Dir: '/Users/yildirim/Desktop/ITSBoard/ITS-BRD-VSC/Programs/Aufgabe1/tmp/1/CMakeFiles/CMakeScratch/TryCompile-s6VgO2']
        ignore line: []
        ignore line: [Run Build Command(s): /Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.ninja.build.ninja/1.12.1/ninja -v cmTC_467d5]
        ignore line: [[1/2] /Users/yildirim/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.24.0/bin//armclang --target=arm-arm-none-eabi   --target=arm-arm-none-eabi -mcpu=Cortex-M4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard    -v -MD -MT CMakeFiles/cmTC_467d5.dir/CMakeCCompilerABI.o -MF CMakeFiles/cmTC_467d5.dir/CMakeCCompilerABI.o.d -o CMakeFiles/cmTC_467d5.dir/CMakeCCompilerABI.o -c /Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeCCompilerABI.c]
        ignore line: [Product: Keil MDK Community (non-commercial free of charge)]
        ignore line: [Component: Arm Compiler for Embedded 6.24]
        ignore line: [Tool: armclang [5f371900]]
        ignore line: []
        ignore line: [Target: arm-arm-none-eabi]
        ignore line: [ (in-process)]
        ignore line: [ "/Users/yildirim/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.24.0/bin/armclang" -cc1 -triple thumbv7em-arm-none-eabihf -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model static -mframe-pointer=none -menable-no-infs -menable-no-nans -fmath-errno -fno-signed-zeros -fdenormal-fp-math=preserve-sign preserve-sign -ffp-contract=on -fno-rounding-math -ffinite-math-only -mconstructor-aliases -target-cpu cortex-m4 -target-feature -vfp2 -target-feature +vfp2sp -target-feature -vfp3 -target-feature -vfp3d16 -target-feature +vfp3d16sp -target-feature -vfp3sp -target-feature +fp16 -target-feature -vfp4 -target-feature -vfp4d16 -target-feature +vfp4d16sp -target-feature -vfp4sp -target-feature -fp-armv8 -target-feature -fp-armv8d16 -target-feature -fp-armv8d16sp -target-feature -fp-armv8sp -target-feature -fullfp16 -target-feature -fp64 -target-feature -d32 -target-feature -neon -target-feature -sha2 -target-feature -aes -target-feature -fp16fml -target-abi aapcs -mfloat-abi hard -debugger-tuning=gdb -fforce-dwarf-frame -fdebug-compilation-dir=/Users/yildirim/Desktop/ITSBoard/ITS-BRD-VSC/Programs/Aufgabe1/tmp/1/CMakeFiles/CMakeScratch/TryCompile-s6VgO2 -target-linker-version 820.1 -v -ffunction-sections -fdata-sections -fcoverage-compilation-dir=/Users/yildirim/Desktop/ITSBoard/ITS-BRD-VSC/Programs/Aufgabe1/tmp/1/CMakeFiles/CMakeScratch/TryCompile-s6VgO2 -resource-dir /Users/yildirim/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.24.0/lib/clang/20 -dependency-file CMakeFiles/cmTC_467d5.dir/CMakeCCompilerABI.o.d -MT CMakeFiles/cmTC_467d5.dir/CMakeCCompilerABI.o -sys-header-deps -internal-isystem /Users/yildirim/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.24.0/bin/../include -nobuiltininc -ferror-limit 19 -fvisibility=hidden -fno-signed-char -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fsuppress-licensing -aggressive-jump-threading -o CMakeFiles/cmTC_467d5.dir/CMakeCCompilerABI.o -x c /Users/yildirim/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.28.4/share/cmake-3.28/Modules/CMakeCCompilerABI.c]
        ignore line: [Arm Compiler for Embedded 6.24 -cc1 default target aarch64-arm-none-eabi]
        ignore line: [#include "..." search starts here:]
        ignore line: [#include <...> search starts here:]
        ignore line: [ /Users/yildirim/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.24.0/bin/../include]
        ignore line: [End of search list.]
        ignore line: [[2/2] : && /Users/yildirim/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.24.0/bin/armar --create -cr libcmTC_467d5.a  CMakeFiles/cmTC_467d5.dir/CMakeCCompilerABI.o && :]
        ignore line: []
        ignore line: []
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
...
